Repository UNLV-CS472-672/2025-S-GROUP4-EulogyQuest, pull requests merged in 2025-03, with the labels that each got.

#7 Adding whitelist section for NPCs we add or change. Closes #6
  .gitignore
Labels: enhancement, workflow

#13 Eul 65 9 kh whitelist bug
  .gitignore
  server/quests/tutorialb/Vahlara.pl
Labels: bug, workflow

#14 Bugfix allowing us to persist and distribute NPC changes (EUL-64/GH-8). Completion of task (EUL-62/GH-5) Demonstrate workflow proficiency.
  server/quests/tutorialb/Vahlara.pl
Labels: bug, good first issue, workflow

#42 [EUL-97]: Updates YouTrack link in PR template to use dash vs underscore
  .github/pull_request_template.md
Labels: enhancement, workflow

#69 EUL-108 Update README.md per johnxu211's suggestion
  README.md
Labels: documentation, enhancement
